### PR TITLE
Add `use App\Entity\Category;` to JobController

### PR DESCRIPTION
**Pull request by BenRoe**
Followed the tutorial an got an error. Guess the problem was, that `use App\Entity\Category;` was not listed to add.

### CODE REVIEW

**Comment by gregurco** [comment]
@BenRoe thank you :+1:

**Comment by BenRoe** [comment]
Also get this error at the end of day 6.
`App\Entity\Job object not found by the @Entity annotation. The expression "repository.findActiveJob(id)" returned null`

**Comment by gregurco** [comment]
@BenRoe and the response code is 404 or 500?

**Comment by BenRoe** [comment]
:confounded: 404

**Comment by gregurco** [comment]
Then it's ok. Simply in dev mode the page is red and stack trace is displayed, but in prod it will be simple 404 page :slightly_smiling_face:

**Pull request merged**
